# Site settings
title: Texas Tribune Style Guides
# email:
description: "These are the style guides for the Texas Tribune."
baseurl: "/styleguides"
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
